version: '3.8'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    hostname: mongo1
    ports:
      - 27017:27017
    volumes:
      - mongo1-data:/data/db
    command: ["--replSet", "rs0"]

  mongo2:
    image: mongo:latest
    container_name: mongo2
    hostname: mongo2
    ports:
      - 27018:27017
    volumes:
      - mongo2-data:/data/db
    command: ["--replSet", "rs0"]

  mongo3:
    image: mongo:latest
    container_name: mongo3
    hostname: mongo3
    ports:
      - 27019:27017
    volumes:
      - mongo3-data:/data/db
    command: ["--replSet", "rs0"]

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:

